name = "NCPlots"
uuid = "bb7f0a92-8966-4c85-beb0-c371d13b1908"
authors = ["Roel Stappers <roels@met.no> and contributors"]
version = "0.1.1"

[deps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.19"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
